# Generated by Django 2.1.5 on 2019-01-25 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkSheet',
            new_name='WorkFlow',
        ),
        migrations.AlterField(
            model_name='state',
            name='owner',
            field=models.ForeignKey(help_text='工单的主审核人', on_delete=django.db.models.deletion.CASCADE, related_name='owner_state', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
    ]
    atomic = False
